import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata = {
	title: "AnomaliMaker",
	description: "Generated by create next app",
	icons: {
		icon: "/anomali.jpeg",
	},
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<head>
				<title>AnomaliMaker</title>
				<link rel="icon" href="/anomali.jpeg" type="image/jpeg" />
			</head>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				{children}
			</body>
		</html>
	);
}
